### PR TITLE
chore: update policy documents

### PR DESCRIPTION
**Pull request by Abhinandan-Purkait**
### Changes

- Update GOVERNANCE
- Update CONTRIBUTING.md
- Update CODE_OF_CONDUCT.md
- Update MAINTAINERS

### CODE REVIEW

**Review by orville-wright — APPROVED** [review]
Approved

**Review by edrob999 — APPROVED** [review]
:thumbsup:
Signed-off-by: Ed Robinson <ed.robinson@gmail.com>

**Review by tiagolobocastro — CHANGES_REQUESTED** [review]
Existing license is MIT

**Review by avishnu — APPROVED** [review]

**Comment by avishnu** [comment]
> Existing license is MIT

There's no existing license file in here, @tiagolobocastro

**Comment by tiagolobocastro** [comment]
> > Existing license is MIT
> 
> There's no existing license file in here, @tiagolobocastro

There's no copy on the repo, it's marked on the crate itself

**Comment by tiagolobocastro** [comment]
https://github.com/openebs/spdk-rs/blob/c4434737f2b5c0640c00332c3f0951743e84ab35/Cargo.toml#L7

**Comment by avishnu** [comment]
> https://github.com/openebs/spdk-rs/blob/c4434737f2b5c0640c00332c3f0951743e84ab35/Cargo.toml#L7

Got it !!

**Review by niladrih — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Pull request merged**
